szchober/urls.py
from django.urls import path
from szchober import views

'''
----------------------------------------------------------------------------------------------------------------
 urls.py file - registers the web apps urls. maps urls for:
    - index
    - sign up
    - become a rider 
    - become a driver
    - find a lift
    - account, driver
    - account, rider
    - about us
    - login
    - logout
    - feedback
    
----------------------------------------------------------------------------------------------------------------
'''

app_name = 'szchober'

urlpatterns = [
    path('', views.index, name='index'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('become-a-rider/', views.become_rider, name='become-a-rider'),
    path('become-a-driver/', views.become_driver, name='become-a-driver'),
    path('my-account-rider/', views.myAccount_rider, name='my_rider_account'),
    path('find-a-lift/', views.find_lift, name='find_a_lift'),
    path('my-account-driver/', views.myAccount_driver, name='my_driver_account'),
    path('about-us/', views.about, name='about-us'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('feedback/', views.feedback, name='feedback'),
]

szchober_project/urls.py
from django.contrib import admin
from django.urls import path, include
from szchober import views

'''
----------------------------------------------------------------------------------------------------------------
 urls.py file - registers the web apps urls. maps urls for:
    - index
    - about us
    - feedback

Heather 2375346c, finished 31/03/20
----------------------------------------------------------------------------------------------------------------
'''

urlpatterns = [
    path('', views.index, name='szchober'),
    path('about-us/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('sign-up/', views.sign_up, name='signup'),
    path('szchober/', include('szchober.urls')),
    path('admin/', admin.site.urls),
]

szchober/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser, AbstractBaseUser

'''
----------------------------------------------------------------------------------------------------------------
 models.py file - Szchober database
There are multiple models in this database
I have created a CustomUser model that allows for a cusomised version of the provided User model from Django
- CustomUser, User and UserProfile all relate to the user creating their own user account
- The Driver and Rider models are the two user models. There are two user models as different user 
    information is needed depending on the user type. If a user is a "Driver" then their address and postcode
    is not needed. Instead, they must provide their car make and model and their registration number.
    However, if a user is a Rider, they should not have to provide vehicle information. Instead they need 
    to provide their address and postcode so that a driver can collect them.
    
- The Lift model stores the data relating to the data that is needed when a rider chooses such as the start destination,
    end destination, total distance and price
    
- The Feedback model is to do with the user's feedback on Szchober - their comment and rating is stored so 
    that it is easily read.
    
- The Rating Model is stores a user's rating on another user.  

----------------------------------------------------------------------------------------------------------------
'''


# Create your models here.

class CustomUser(AbstractUser):
    type_choices = (
        ('D', 'Driver'),
        ('R', 'Rider'),

    )
    user_type = models.CharField(max_length=1,
                                 choices=type_choices,
                                 default='')


class UserDetails(models.Model):
    type = models.OneToOneField('CustomUser', on_delete=models.CASCADE)


class Driver(AbstractBaseUser):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
    # username = models.CharField(max_length=20, default='')
    forename = models.CharField(max_length=16, default='')
    surname = models.CharField(max_length=16, default='')
    password = models.CharField(max_length=20, default='')
    email = models.EmailField(max_length=30, unique=True, default='')
    phone_number = models.CharField(max_length=11, default='')
    rating = models.IntegerField(default=5)
    review = models.CharField(max_length=128, default='')
    driver_id = models.CharField(max_length=10, unique=True, default='')
    car_make = models.CharField(max_length=10, default='')
    car_model = models.CharField(max_length=10, default='')
    car_registration = models.CharField(max_length=8, unique=True, default='')
    availability = models.BooleanField(default=False)
    is_driver = models.BooleanField(default=True)

    USERNAME_FIELD = 'driver_id'

    def __str__(self):
        return self.driver_id


class Rider(AbstractBaseUser):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
    # username = models.CharField(max_length=20, default='')
    forename = models.CharField(max_length=16, default='')
    surname = models.CharField(max_length=16, default='')
    password = models.CharField(max_length=20, default='')
    email = models.EmailField(max_length=30, unique=True, default='')
    phone_number = models.CharField(max_length=11, default='')
    rating = models.IntegerField(default=5)
    review = models.CharField(max_length=128, default='')
    address = models.CharField(max_length=128, default='')
    postcode = models.CharField(max_length=7, default='')
    rider_id = models.CharField(max_length=10, unique=True, default='')
    is_rider = models.BooleanField(default=True)

    USERNAME_FIELD = 'rider_id'

    def __str__(self):
        return self.rider_id


class Lift(models.Model):
    lift_id = models.CharField(max_length=10, unique=True, default='')
    start = models.CharField(max_length=10, default='')
    end = models.CharField(max_length=10, default='')
    distance = models.FloatField()
    price = models.FloatField()

    def __str__(self):
        return self.lift_id


class Feedback(models.Model):
    name = models.CharField(max_length=20, default='')
    description = models.TextField(max_length=500, default='')

    class Meta:
        verbose_name_plural = 'Feedback'

    def __str__(self):
        return self.name


class Rating(models.Model):
    rating_id = models.CharField(max_length=10, unique=True, default='')
    description = models.CharField(max_length=500, default='')
    rating = models.IntegerField(default=5)

    def __str__(self):
        return self.rating_id


class User(models.Model):
    is_rider = models.BooleanField(default=False)
    is_driver = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return "User"

szchober/forms.py
from django.contrib.auth.models import User
from szchober.models import UserProfile, Rider, Driver, Feedback
from django import forms

'''
----------------------------------------------------------------------------------------------------------------
 forms.py file - Creates forms for both user types so they can log in and create an account
 - UserFormDriver - ties to the Driver model, allows user to create password and takes 
    in the relevant data that a driver user must give.
- UserFormRider - ties to the Rider model, allows user to create password and takes
    in the relevant data that a rider user must give
- UserProfileForm - ties to the UserProfile model, allows users to upload a picture.

----------------------------------------------------------------------------------------------------------------
'''


class UserFormDriver(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Driver
        fields = ('forename', 'surname', 'email', 'password', 'phone_number',
                  'car_make', 'car_model', 'car_registration', 'driver_id',)


class UserFormRider(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Rider
        fields = ('forename', 'surname', 'email', 'password', 'phone_number', 'address', 'postcode',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('name', 'description')

szchober/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.models import User
from szchober.models import UserProfile
from szchober.forms import UserFormDriver, UserFormRider, UserProfileForm, FeedbackForm

from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

'''
----------------------------------------------------------------------------------------------------------------
 views.py file - registers the web apps views for the urls. creates views for:
    - index
    - sign up
    - become a rider 
    - become a driver
    - find a lift
    - account, driver
    - account, rider
    - about us
    - login
    - logout
    - feedback
----------------------------------------------------------------------------------------------------------------
'''


def index(request):
    return render(request, 'szchober/index.html')


def sign_up(request):
    return render(request, 'szchober/sign-up.html')


def become_rider(request):
    registered = False
    if request.method == 'POST':
        user_form = UserFormRider(request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserFormRider()
        profile_form = UserProfileForm()

    return render(request,
                  'szchober/become-a-rider.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def become_driver(request):
    registered = False
    if request.method == 'POST':
        user_form = UserFormDriver(request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserFormDriver()
        profile_form = UserProfileForm()

    return render(request,
                  'szchober/become-a-driver.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def myAccount_rider(request):
    return HttpResponse("this is my rider account")


def myAccount_driver(request):
    return HttpResponse("this is my driver account")


def find_lift(request):
    return render(request, 'szchober/find-a-lift.html')


def about(request):
    return render(request, 'szchober/about-us.html')


def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,"Feedback Submitted Sucessfully")
    else:
        form = FeedbackForm()

    return render(request, 'szchober/feedback.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('szchober:index'))
            else:
                return HttpResponse("Your account is disabled")
        else:
            print("Invalid login details")
            return HttpResponse("Invalid login details supplied" + "<br><a href='/szchober/'>Homepage</a>")
    else:
        return render(request, 'szchober/login.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('szchober:index'))

templates/szchober/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>

    <title>Szchober -
		   {% block title_block %}

		   {% endblock %}
	</title>
      <link rel="icon" href="{% static 'images/car-icon.png' %}">
	  <link rel="stylesheet" href="{% static 'styles/templatestyles.css' %}" />
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
      <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!--
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
-->
<meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>

<header id="main-header"style="background-color:white;">
            <div class="main-header">
                <a href="{% url 'szchober:index' %}"><h1>Szch<span>&#246</span>ber.</h1></a>

            </div>
        </header>
           <nav class="navbar navbar-inverse"style="background-color:white; margin-bottom:0px;">
			    <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'szchober:become-a-driver' %}">Driver</a></li>
                    <li><a href="{% url 'szchober:become-a-rider' %}">Rider</a></li>
                    <li ><a href="{% url 'szchober:about-us' %}">About us</a></li>
                </ul>
               <ul class="nav navbar-nav navbar-right">
                    {% if registered %}
                    <li class="login"><a href="#">My Account</a></li>
                    {% else %}
                    <li class="login"><a href="#" id="modalbutton">Log in</a></li>
                    <li class="signup"><a href="{% url 'szchober:sign-up' %}" >Sign up</a></li>
                    {% endif %}
                </ul>
                    </div>
            </nav>
    <div class="container-fluid" style="padding:100px; background-color: lightgray; z-index:-1">
    {% block body_block %}
    {% endblock %}
    </div>


    <!-- Site footer -->
    <footer class="site-footer" style="z-index: 300; position:relative;" >
      <div class="container" >
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">We aim to provide the best car-sharing experience for the community with goals of improving your daily commuting lifestyle</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Contact us</h6>
            <ul class="footer-links">
              <li><h6>Email:</h6></li>
              <li>support@szchober.com</li>
              <li><h6>Phone:</h6></li>
              <li>+44 749 4671 324</li>
              <li><h6>Helpdesk Opening Hours:</h6></li>
              <li>8.30am to 7pm</li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="{% url 'szchober:feedback' %}">Feedback</a></li>
              <li><a href="{% url 'szchober:about-us' %}">About Us</a></li>
              <li>Download Szchober App Here:</a></li>
                <li><a href="http://hyperurl.co/pt4i93"><img src="{% static 'images/download-on-app-store-png-2.png' %}" alt="appstore"></a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by
         Szchober.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="https://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="https://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="https://www.instagram.com"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="https://www.linkedin.com"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>


  <script src="{% static 'js/rango-query.js' %}" crossorigin="anonymous"></script>
  </body>
</html>

templates/szchober/become-a-driver-with-modal(not needed).html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <!-- llllllllllllllllllllllllllll -->
<meta name="viewport" content="width=device-width, initial-scale=1">

    <head>
        <title>Szch&#246ber.</title>
        <!--<link rel="stylesheet" href="{% static "styles/templatestyles.css" %}" /> -->
        <link rel="stylesheet" href="../../static/styles/templatestyles.css">
    </head>
    <body>
        <header id="main-header">
            <div class="main-header">
                <a href="#"><h1>Szch<span>&#246</span>ber.</h1></a>

            </div>
        </header>
            <nav id="navbar">
                <ul class="navbar-left">
                    <li><a href="#">Driver</a></li>
                    <li><a href="#">Rider</a></li>
                    <li ><a href="#" style="color: rgb(44, 131, 83)">About us</a></li>
                </ul>
                <ul class="navbar-right">
                    <li class="login"><a href="#" id="modalbutton">Log in</a></li>
                    <li class="signup"><a href="#" style="color: rgb(44, 131, 83);">Sign up</a></li>
                </ul>
            </nav>
            <h1 style="font-size: 18pt; visibility: hidden;">You can't see me</h1>
            <br>

            <section class="boxed" >
                <div>
                    <h3 style="display: inline;">Become a Driver</h3>
                </div>
                <div>
                    <h3 style="display: inline;">Register</h3>
                </div>
                <div>
                    <a href="{% url 'szchober:become-a-rider' %}"><img src="../../static/images/carf.png" alt="car" style= "width: 300px; border: 2px rgb(44, 131, 83) solid; background-color: #64A874;" ></a>
                    <br>
                </div>
                <div>
                    <div style="border: 2px  rgb(44, 131, 83) solid; width: 300px; height: 300px; padding-top: 4%; ">
                        

                        <!-- Input database file here -->
                        <form action="process.php" method="POST">
                            <div>
                                <div class="twoperline">
                                    <input type="text" name="forename" placeholder="Forename"  >
                                    <input type="text" name="surname" placeholder="Surname" >
                                </div>
                                <input class="oneperline" type="email" name="email" placeholder="Email">
                                <input class="oneperline" type="password" name="password" placeholder="Password">
                                <input class="oneperline" type="tel" name="phone" placeholder="Phone Number">
                                <div class="twoperline">
                                    <input type="text" name="carmake" placeholder="Car Make"> 
                                    <input type="text" name="carmodel" placeholder="Car Model" >
                                </div>
                                <input class="oneperline" type="text" name="regplate" placeholder="Registration Plate">
                                <input class="submitbutton" type="submit" name="submit" value="Submit">





                            </div>
                        </form>

                    </div>
                </div>
    </section>     




<!--
{% load staticfiles %}

{% block title_block %}
{% endblock %}

{% block body_block %}
<h1>Become a Driver</h1>
{% if registered %}
Rango says:<strong>thank you for registering!</strong>
<a href="{%url 'szchober:index'%}">Return to the homepage.</a><br/>
{% else %}
<strong>register here!</strong><br/>

<form id="user_form" method="post" action="{% url 'szchober:become-a-driver' %}"
    enctype="multipart/form-data">

    {% csrf_token %}

    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}
-->
        
    </section>
    <footer>
        <br>
        <nav id="navbar">
            <ul class="navbar-left">
                <li><a href="#"><img src="../../static/images/420px-Globe_icon.svg.png" alt=""></a></li>
                <li><a href="#">
                    <div>
                        <h3 style="color: black;">Contact us</h3>
                        <h1 style="color: rgb(44, 131, 83); font-size: 10px; padding-top: 5px ;">+44 749 4671 324</h1>
                        <a href="{% url 'szchober:feedback' %}"><h1 style="color: rgb(44, 131, 83); font-size: 10px; padding-top: 5px ;">Feedback</h1></a>
                    </div>
                </a></li>
            </ul>
            <ul class="navbar-right">
                <li><a href="http://hyperurl.co/pt4i93"><img src="../../static/images/download-on-app-store-png-2.png" alt=""></a></li>
                <li><a href="#"><img src="../../static/images/socials.png" alt=""></a></li>
            </ul>
        </nav>
    </footer>


    <div id="loginmodal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>Log in</h3>
            <form action="process.php" method="POST">
                <input class="oneperline" placeholder="Email" type="text" name="loginemail">
                <input class="oneperline" placeholder="Password" type="text" name="loginpassword">
                <input class="submitbutton" type="submit" name="loginbutton" value="Sign me in" style="float: right;">
                
                
            </form>

        </div>
      
    </div>
      
    <script>
        var modal = document.getElementById("loginmodal");
        var btn = document.getElementById("modalbutton");
        var span = document.getElementsByClassName("close")[0];
        btn.onclick = function() {
            modal.style.display = "block";
        }
        span.onclick = function() {
            modal.style.display = "none";
        }
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>
      
    </body>
</html>

templates/szchober/become-a-driver-with-modal.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <!-- llllllllllllllllllllllllllll -->
<meta name="viewport" content="width=device-width, initial-scale=1">

    <head>
        <title>Szch&#246ber.</title>
        <!--<link rel="stylesheet" href="{% static "styles/templatestyles.css" %}" /> -->
        <link rel="stylesheet" href="../../static/styles/templatestyles.css">
    </head>
    <body>
        <header id="main-header">
            <div class="main-header">
                <a href="#"><h1>Szch<span>&#246</span>ber.</h1></a>

            </div>
        </header>
            <nav id="navbar">
                <ul class="navbar-left">
                    <li><a href="#">Driver</a></li>
                    <li><a href="#">Rider</a></li>
                    <li ><a href="#" style="color: rgb(44, 131, 83)">About us</a></li>
                </ul>
                <ul class="navbar-right">
                    <li class="login"><a href="#" id="modalbutton">Log in</a></li>
                    <li class="signup"><a href="#" style="color: rgb(44, 131, 83);">Sign up</a></li>
                </ul>
            </nav>
            <h1 style="font-size: 18pt; visibility: hidden;">You can't see me</h1>
            <br>

            <section class="boxed" >
                <div>
                    <h3 style="display: inline;">Become a Driver</h3>
                </div>
                <div>
                    <h3 style="display: inline;">Register</h3>
                </div>
                <div>
                    <a href="{% url 'szchober:become-a-rider' %}"><img src="../../static/images/carf.png" alt="car" style= "width: 300px; border: 2px rgb(44, 131, 83) solid; background-color: #64A874;" ></a>
                    <br>
                </div>
                <div>
                    <div style="border: 2px  rgb(44, 131, 83) solid; width: 300px; height: 300px; padding-top: 4%; ">
                        

                        <!-- Input database file here -->
                        <form action="process.php" method="POST">
                            <div>
                                <div class="twoperline">
                                    <input type="text" name="forename" placeholder="Forename"  >
                                    <input type="text" name="surname" placeholder="Surname" >
                                </div>
                                <input class="oneperline" type="email" name="email" placeholder="Email">
                                <input class="oneperline" type="password" name="password" placeholder="Password">
                                <input class="oneperline" type="tel" name="phone" placeholder="Phone Number">
                                <div class="twoperline">
                                    <input type="text" name="carmake" placeholder="Car Make"> 
                                    <input type="text" name="carmodel" placeholder="Car Model" >
                                </div>
                                <input class="oneperline" type="text" name="regplate" placeholder="Registration Plate">
                                <input class="submitbutton" type="submit" name="submit" value="Submit">





                            </div>
                        </form>

                    </div>
                </div>
    </section>     




<!--
{% load staticfiles %}

{% block title_block %}
{% endblock %}

{% block body_block %}
<h1>Become a Driver</h1>
{% if registered %}
Rango says:<strong>thank you for registering!</strong>
<a href="{%url 'szchober:index'%}">Return to the homepage.</a><br/>
{% else %}
<strong>register here!</strong><br/>

<form id="user_form" method="post" action="{% url 'szchober:become-a-driver' %}"
    enctype="multipart/form-data">

    {% csrf_token %}

    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}
-->
        
    </section>
    <footer>
        <br>
        <nav id="navbar">
            <ul class="navbar-left">
                <li><a href="#"><img src="../../static/images/420px-Globe_icon.svg.png" alt=""></a></li>
                <li><a href="#">
                    <div>
                        <h3 style="color: black;">Contact us</h3>
                        <h1 style="color: rgb(44, 131, 83); font-size: 10px; padding-top: 5px ;">+44 749 4671 324</h1>
                        <a href="{% url 'szchober:feedback' %}"><h1 style="color: rgb(44, 131, 83); font-size: 10px; padding-top: 5px ;">Feedback</h1></a>
                    </div>
                </a></li>
            </ul>
            <ul class="navbar-right">
                <li><a href="http://hyperurl.co/pt4i93"><img src="../../static/images/download-on-app-store-png-2.png" alt=""></a></li>
                <li><a href="#"><img src="../../static/images/socials.png" alt=""></a></li>
            </ul>
        </nav>
    </footer>


    <div id="loginmodal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>Log in</h3>
            <form action="process.php" method="POST">
                <input class="oneperline" placeholder="Email" type="text" name="loginemail">
                <input class="oneperline" placeholder="Password" type="text" name="loginpassword">
                <input class="submitbutton" type="submit" name="loginbutton" value="Sign me in" style="float: right;">
                
                
            </form>

        </div>
      
    </div>
      
    <script>
        var modal = document.getElementById("loginmodal");
        var btn = document.getElementById("modalbutton");
        var span = document.getElementsByClassName("close")[0];
        btn.onclick = function() {
            modal.style.display = "block";
        }
        span.onclick = function() {
            modal.style.display = "none";
        }
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>
      
    </body>
</html>

templates/szchober/login.html
{% extends 'szchober/base.html' %}
{% load staticfiles %}
{% block title_block %} Login
{% endblock %}
{% block body_block %}
<h1>Login to Szchober</h1>
<form id="login_form" method="post" action="{% url 'szchober:login' %}">
{% csrf_token %}
Username: <input type="text" name="username" value="" size="50" /> <br />
Password: <input type="password" name="password" value="" size="50" /> <br />
<input type="submit" value="submit" />
</form>
{% endblock %}

templates/szchober/logout.html
<!DOCTYPE html>
{% extends 'szchober/base.html' %}
<html>

{% block title_block %}Log out{% endblock %}

{% block body_block %}
<h2>You have logged out<h2/>
<li><a href="{% url 'rango:index' %}">Index</a></li>
    {% endblock %}
</html>

templates/szchober/register.html
{% extends 'szchober/base.html' %}
{% load staticfiles %}

{% block title_block %}
Register!
{% endblock %} 

{% block body_block %}
<h1>Register for Szchober</h1>
{% if registered %}
Rango says:<strong>thank you for registering!</strong>
<a href="{%url 'szchober:index'%}">Return to the homepage.</a><br/>
{% else %}
<strong>register here!</strong><br/>

<form id="user_form" method="post" action="{% url 'szchober:register' %}"
    enctype="multipart/form-data">

    {% csrf_token %}

    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}